spring:
  profiles:
    active: dev

---
server:
  port: 7001

spring:
  profiles: dev
  application:
    name: spring-cloud-eureka
eureka:
  instance:
    hostname: eureka7001.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否向Eureka注册中心注册自己
    fetch-registry: false #如果为false表示自己为注册中心
    service-url: #监控页面
      # 单击：http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群（关联）：关联7002 和 7003
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

---
server:
  port: 7002

spring:
  profiles: test
  application:
    name: spring-cloud-eureka
eureka:
  instance:
    hostname: eureka7001.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否向Eureka注册中心注册自己
    fetch-registry: false #如果为false表示自己为注册中心
    service-url: #监控页面
      # 单击：http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群（关联）：关联7001 和 7003
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/